import type {
  ApprovalItem,
  Department,
  FileItem,
  Meeting,
  Project,
  Stat,
  TaskItem,
  TeamMember,
} from "./types";

export const departments: Department[] = [
  { id: "chiefs-office", name: "Chief's Office", taskCount: 18, icon: "landmark" },
  { id: "major-projects", name: "Major Projects", taskCount: 47, badge: 5, icon: "folder-kanban" },
  { id: "lands", name: "Lands", taskCount: 12, icon: "map" },
  { id: "forestry", name: "Forestry", taskCount: 8, icon: "trees" },
  { id: "housing", name: "Housing", taskCount: 6, icon: "home" },
  { id: "capital-projects", name: "Capital Projects", taskCount: 9, icon: "hard-hat" },
  { id: "finance", name: "Finance", taskCount: 4, icon: "wallet" },
];

export const sidebarNav = {
  dashboard: { id: "dashboard", label: "Dashboard", href: "/dashboard" },
  departments: [
    { id: "chiefs-office", label: "Chief's Office", href: "/departments/chiefs-office" },
    { id: "major-projects", label: "Major Projects", href: "/departments/major-projects", badge: 5 },
    { id: "lands", label: "Lands", href: "/departments/lands" },
    { id: "forestry", label: "Forestry", href: "/departments/forestry" },
    { id: "housing", label: "Housing", href: "/departments/housing" },
  ],
  operations: [
    { id: "capital-projects", label: "Capital Projects", href: "/departments/capital-projects" },
    { id: "finance", label: "Finance", href: "/finance" },
  ],
  office: [
    { id: "approvals", label: "Needs Approval", href: "/approvals", badge: 3 },
    { id: "files", label: "Documents", href: "/files" },
    { id: "tasks", label: "Tasks", href: "/tasks" },
    { id: "reports", label: "Reports", href: "/reports" },
    { id: "settings", label: "Settings", href: "/settings" },
  ],
};

export const projects: Project[] = [
  // Major Projects
  {
    id: "kemess-north",
    name: "Kemess North",
    departmentId: "major-projects",
    status: "active",
    lead: "Terry",
    priority: "urgent",
    progress: 78,
    due: "May 13, 2026",
    summary: "Final TKN letter and signature package with Centerra.",
    description:
      "Nation-to-company engagement on Kemess North culminating in the final Takla Nation (TKN) letter and Chief signature package. Includes supporting annexes, legal Schedule B confirmation, and Centerra acknowledgment.",
    started: "Jan 14, 2026",
    stakeholders: ["Chief French", "Terry", "Evan", "Centerra", "Legal"],
    taskCount: 14,
    fileCount: 9,
  },
  {
    id: "fpx",
    name: "FPX Share-holding",
    departmentId: "major-projects",
    status: "at-risk",
    lead: "Terry",
    priority: "high",
    progress: 45,
    due: "May 15, 2026",
    summary: "Board decision briefing on share-holding position.",
    description:
      "Executive decision file for FPX share-holding. Finance valuation, governance rights, and membership optics must be settled before the board briefing.",
    started: "Feb 3, 2026",
    stakeholders: ["Chief French", "Terry", "Priya", "Board"],
    taskCount: 11,
    fileCount: 6,
  },
  {
    id: "pathways",
    name: "Pathways",
    departmentId: "major-projects",
    status: "active",
    lead: "Evan",
    priority: "high",
    progress: 62,
    due: "May 20, 2026",
    summary: "Dispute resolution brief and legal coordination.",
    description:
      "Dispute resolution brief spanning Major Projects, Lands referrals, and legal posture. Chronology and cross-department inputs feed the Chief approval package.",
    started: "Mar 12, 2026",
    stakeholders: ["Evan", "Scott", "Terry", "Legal"],
    taskCount: 9,
    fileCount: 5,
  },
  {
    id: "iba-amendment",
    name: "IBA Amendment",
    departmentId: "major-projects",
    status: "active",
    lead: "Terry",
    priority: "high",
    progress: 55,
    due: "May 28, 2026",
    summary: "Impact Benefit Agreement amendment package for signature.",
    description:
      "Impact Benefit Agreement amendment covering employment targets, revenue sharing, and dispute escalation. Redlines open on clauses 4.2 and 7.1.",
    started: "Mar 1, 2026",
    stakeholders: ["Terry", "Chief French", "Legal"],
    taskCount: 8,
    fileCount: 4,
  },
  {
    id: "mining-referrals",
    name: "Mining Referrals Q2",
    departmentId: "major-projects",
    status: "on-hold",
    lead: "Evan",
    priority: "medium",
    progress: 30,
    due: "Jun 12, 2026",
    summary: "Batch of Q2 mining referral responses under review.",
    description:
      "Batch processing of Q2 mining referral responses. On hold pending capacity after Kemess and FPX close.",
    started: "Apr 1, 2026",
    stakeholders: ["Evan", "Scott"],
    taskCount: 5,
    fileCount: 3,
  },
  // Lands
  {
    id: "referral-response",
    name: "Referral Response Program",
    departmentId: "lands",
    status: "active",
    lead: "Scott",
    priority: "urgent",
    progress: 70,
    due: "May 12, 2026",
    summary: "Flag and respond to outstanding land referrals.",
    taskCount: 6,
    fileCount: 4,
  },
  {
    id: "traditional-use",
    name: "Traditional Use Study",
    departmentId: "lands",
    status: "active",
    lead: "Scott",
    priority: "medium",
    progress: 40,
    due: "Jun 30, 2026",
    summary: "Map traditional use areas for upcoming consultations.",
    taskCount: 4,
    fileCount: 3,
  },
  {
    id: "boundary-survey",
    name: "Boundary Survey — North Parcel",
    departmentId: "lands",
    status: "active",
    lead: "Scott",
    priority: "high",
    progress: 25,
    due: "Jul 15, 2026",
    summary: "Survey coordination for north parcel clarification.",
    taskCount: 2,
    fileCount: 2,
  },
  // Forestry
  {
    id: "cutting-permit",
    name: "Cutting Permit Package",
    departmentId: "forestry",
    status: "active",
    lead: "Daniel",
    priority: "urgent",
    progress: 58,
    due: "May 20, 2026",
    summary: "Assemble and submit cutting permit documentation.",
    taskCount: 5,
    fileCount: 4,
  },
  {
    id: "silviculture",
    name: "Silviculture Plan 2026",
    departmentId: "forestry",
    status: "active",
    lead: "Daniel",
    priority: "medium",
    progress: 35,
    due: "Jun 8, 2026",
    summary: "Annual silviculture planning and contractor RFP.",
    taskCount: 3,
    fileCount: 2,
  },
  // Housing
  {
    id: "allocation-2026",
    name: "Housing Allocation 2026",
    departmentId: "housing",
    status: "active",
    lead: "Maria",
    priority: "high",
    progress: 80,
    due: "May 18, 2026",
    summary: "Waitlist review and unit assignment letters.",
    taskCount: 4,
    fileCount: 3,
  },
  {
    id: "renovation-program",
    name: "Home Renovation Program",
    departmentId: "housing",
    status: "active",
    lead: "Maria",
    priority: "medium",
    progress: 50,
    due: "Jun 20, 2026",
    summary: "Priority renovations for occupied band housing.",
    taskCount: 2,
    fileCount: 2,
  },
  // Capital Projects
  {
    id: "community-hall",
    name: "Community Hall Upgrade",
    departmentId: "capital-projects",
    status: "active",
    lead: "Terry",
    priority: "high",
    progress: 42,
    due: "Aug 1, 2026",
    summary: "Structural upgrade and accessibility improvements.",
    taskCount: 5,
    fileCount: 4,
  },
  {
    id: "water-infrastructure",
    name: "Water Infrastructure Phase 2",
    departmentId: "capital-projects",
    status: "at-risk",
    lead: "Finance",
    priority: "urgent",
    progress: 33,
    due: "Jul 10, 2026",
    summary: "Phase 2 water line expansion — contractor delay risk.",
    taskCount: 4,
    fileCount: 3,
  },
  // Finance
  {
    id: "q2-budget",
    name: "Q2 Budget Cycle",
    departmentId: "finance",
    status: "active",
    lead: "Finance",
    priority: "high",
    progress: 65,
    due: "May 22, 2026",
    summary: "Variance reporting and department budget checkpoints.",
    taskCount: 3,
    fileCount: 2,
  },
  {
    id: "audit-prep",
    name: "Annual Audit Prep",
    departmentId: "finance",
    status: "active",
    lead: "Finance",
    priority: "medium",
    progress: 20,
    due: "Sep 1, 2026",
    summary: "Document collection for external audit readiness.",
    taskCount: 1,
    fileCount: 1,
  },
  // Chief's Office
  {
    id: "bcr-may",
    name: "Band Council Resolutions — May",
    departmentId: "chiefs-office",
    status: "completed",
    lead: "Chief French",
    priority: "high",
    progress: 100,
    due: "May 5, 2026",
    summary: "May BCR package signed and filed.",
    taskCount: 2,
    fileCount: 2,
  },
  {
    id: "exec-directives",
    name: "Executive Directives Tracker",
    departmentId: "chiefs-office",
    status: "active",
    lead: "Chief French",
    priority: "high",
    progress: 55,
    due: "May 31, 2026",
    summary: "Open directives to department heads this cycle.",
    taskCount: 8,
    fileCount: 3,
  },
];

export const stats: Stat[] = [
  {
    id: "active-files",
    label: "Active files",
    value: 12,
    subtitle: "All departments",
    icon: "folder",
    color: "green",
  },
  {
    id: "total-tasks",
    label: "Total tasks",
    value: 81,
    subtitle: "8 assignees",
    icon: "list",
    color: "blue",
  },
  {
    id: "urgent",
    label: "Urgent",
    value: 14,
    subtitle: "Action needed now",
    icon: "alert",
    color: "red",
  },
  {
    id: "high",
    label: "High priority",
    value: 28,
    subtitle: "This month",
    icon: "star",
    color: "orange",
  },
  {
    id: "completed",
    label: "Completed",
    value: 2,
    subtitle: "This cycle",
    icon: "check",
    color: "green",
  },
];

export const alertItems = [
  "TKN letter (Kemess North)",
  "FPX share-holding decision",
  "Pathways dispute resolution brief",
];

export const approvals: ApprovalItem[] = [
  {
    id: "a1",
    title: "TKN letter — Kemess North",
    subtitle: "Ready for Chief signature",
    action: "sign",
    icon: "pen",
    departmentId: "chiefs-office",
    projectId: "kemess-north",
  },
  {
    id: "a2",
    title: "FPX — Share-holding decision",
    subtitle: "Decision required",
    action: "decide",
    icon: "dollar",
    departmentId: "chiefs-office",
    projectId: "fpx",
  },
  {
    id: "a3",
    title: "Pathways — Dispute resolution brief",
    subtitle: "Review & approve",
    action: "review",
    icon: "file",
    departmentId: "chiefs-office",
    projectId: "pathways",
  },
  {
    id: "a4",
    title: "Band Council Resolution — May",
    subtitle: "Signed May 5",
    action: "done",
    icon: "check",
    departmentId: "chiefs-office",
    projectId: "bcr-may",
  },
  {
    id: "a5",
    title: "Housing — Allocation letter",
    subtitle: "Signed May 2",
    action: "done",
    icon: "check",
    departmentId: "housing",
    projectId: "allocation-2026",
  },
  {
    id: "a6",
    title: "Forestry — Cutting permit package",
    subtitle: "Ready for review",
    action: "review",
    icon: "file",
    departmentId: "forestry",
    projectId: "cutting-permit",
  },
  {
    id: "a7",
    title: "Lands — Referral response",
    subtitle: "Decision required",
    action: "decide",
    icon: "dollar",
    departmentId: "lands",
    projectId: "referral-response",
  },
  {
    id: "a8",
    title: "Major Projects — IBA amendment",
    subtitle: "Ready for Chief signature",
    action: "sign",
    icon: "pen",
    departmentId: "major-projects",
    projectId: "iba-amendment",
  },
  {
    id: "a9",
    title: "Kemess North — Supporting annex",
    subtitle: "Review before signature package",
    action: "review",
    icon: "file",
    departmentId: "major-projects",
    projectId: "kemess-north",
  },
  {
    id: "a10",
    title: "FPX — Board memo",
    subtitle: "Decision package for Chief",
    action: "decide",
    icon: "dollar",
    departmentId: "major-projects",
    projectId: "fpx",
  },
  {
    id: "a11",
    title: "Pathways — Legal brief",
    subtitle: "Ready for review",
    action: "review",
    icon: "file",
    departmentId: "major-projects",
    projectId: "pathways",
  },
  {
    id: "a12",
    title: "Water infrastructure change order",
    subtitle: "Capital spend approval",
    action: "decide",
    icon: "dollar",
    departmentId: "capital-projects",
    projectId: "water-infrastructure",
  },
  {
    id: "a13",
    title: "Q2 budget variance report",
    subtitle: "Finance sign-off needed",
    action: "review",
    icon: "file",
    departmentId: "finance",
    projectId: "q2-budget",
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: "jf",
    name: "Chief French",
    role: "Chief's Office",
    initials: "JF",
    color: "#0d7a4f",
    departmentIds: ["chiefs-office", "major-projects"],
    urgentCount: 1,
    highCount: 4,
    taskCount: 18,
    tasks: [
      {
        id: "t1",
        title: "Kemess North — Final TKN letter",
        priority: "urgent",
        project: "Kemess North",
        departmentId: "chiefs-office",
      },
      {
        id: "t2",
        title: "FPX — Share-holding decision",
        priority: "high",
        project: "FPX",
        departmentId: "major-projects",
      },
      {
        id: "t3",
        title: "Pathways — Dispute resolution",
        priority: "high",
        project: "Pathways",
        departmentId: "major-projects",
      },
    ],
  },
  {
    id: "tr",
    name: "Terry",
    role: "Executive Lead",
    initials: "TR",
    color: "#1a6b8a",
    departmentIds: ["major-projects", "capital-projects", "chiefs-office"],
    urgentCount: 3,
    highCount: 2,
    taskCount: 8,
    tasks: [
      {
        id: "t4",
        title: "Aggregate bi-weekly progress updates",
        priority: "urgent",
        project: "Kemess North",
        departmentId: "major-projects",
      },
      {
        id: "t5",
        title: "IBA amendment package",
        priority: "high",
        project: "IBA Amendment",
        departmentId: "major-projects",
      },
      {
        id: "t5b",
        title: "Community hall contractor check-in",
        priority: "high",
        project: "Community Hall Upgrade",
        departmentId: "capital-projects",
      },
    ],
  },
  {
    id: "ev",
    name: "Evan",
    role: "Project Support",
    initials: "EV",
    color: "#6b5b95",
    departmentIds: ["major-projects"],
    urgentCount: 2,
    highCount: 1,
    taskCount: 6,
    tasks: [
      {
        id: "t6",
        title: "Upload Kemess supporting docs",
        priority: "urgent",
        project: "Kemess North",
        departmentId: "major-projects",
      },
      {
        id: "t6b",
        title: "Pathways dispute chronology",
        priority: "high",
        project: "Pathways",
        departmentId: "major-projects",
      },
    ],
  },
  {
    id: "sc",
    name: "Scott",
    role: "Lands",
    initials: "SC",
    color: "#8a6d1a",
    departmentIds: ["lands"],
    urgentCount: 1,
    highCount: 1,
    taskCount: 5,
    tasks: [
      {
        id: "t7",
        title: "Flag referral for Chief attention",
        priority: "urgent",
        project: "Referral Response Program",
        departmentId: "lands",
      },
      {
        id: "t7b",
        title: "Traditional use map draft",
        priority: "high",
        project: "Traditional Use Study",
        departmentId: "lands",
      },
    ],
  },
  {
    id: "mk",
    name: "Maria",
    role: "Housing",
    initials: "MK",
    color: "#8a3a5c",
    departmentIds: ["housing"],
    urgentCount: 0,
    highCount: 2,
    taskCount: 4,
    tasks: [
      {
        id: "t8",
        title: "Allocation waitlist update",
        priority: "high",
        project: "Housing Allocation 2026",
        departmentId: "housing",
      },
      {
        id: "t8b",
        title: "Renovation priority list",
        priority: "high",
        project: "Home Renovation Program",
        departmentId: "housing",
      },
    ],
  },
  {
    id: "dl",
    name: "Daniel",
    role: "Forestry",
    initials: "DL",
    color: "#2d6a4f",
    departmentIds: ["forestry"],
    urgentCount: 1,
    highCount: 1,
    taskCount: 7,
    tasks: [
      {
        id: "t9",
        title: "Cutting permit package",
        priority: "urgent",
        project: "Cutting Permit Package",
        departmentId: "forestry",
      },
      {
        id: "t9b",
        title: "Silviculture contractor shortlist",
        priority: "high",
        project: "Silviculture Plan 2026",
        departmentId: "forestry",
      },
    ],
  },
  {
    id: "fn",
    name: "Priya",
    role: "Finance",
    initials: "PR",
    color: "#1e5a8a",
    departmentIds: ["finance", "capital-projects"],
    urgentCount: 1,
    highCount: 1,
    taskCount: 4,
    tasks: [
      {
        id: "t10",
        title: "Q2 variance report",
        priority: "high",
        project: "Q2 Budget Cycle",
        departmentId: "finance",
      },
      {
        id: "t10b",
        title: "Water phase 2 change order cost",
        priority: "urgent",
        project: "Water Infrastructure Phase 2",
        departmentId: "capital-projects",
      },
    ],
  },
];

export const meetings: Meeting[] = [
  {
    id: "m1",
    dateLabel: "13 MAY",
    title: "Kemess North — Final TKN letter",
    detail: "Signature package review",
    leads: "Leads: Terry · Evan",
    status: "TBC",
    departmentId: "major-projects",
    projectId: "kemess-north",
  },
  {
    id: "m2",
    dateLabel: "NEXT WK",
    title: "FPX share-holding discussion",
    detail: "Board decision briefing",
    leads: "Leads: Terry · Finance",
    status: "TBC",
    departmentId: "major-projects",
    projectId: "fpx",
  },
  {
    id: "m2b",
    dateLabel: "16 MAY",
    title: "Pathways legal sync",
    detail: "Dispute resolution briefing",
    leads: "Leads: Evan · Lands",
    status: "TBC",
    departmentId: "major-projects",
    projectId: "pathways",
  },
  {
    id: "m2c",
    dateLabel: "19 MAY",
    title: "IBA amendment walkthrough",
    detail: "Chief signature prep",
    leads: "Leads: Terry · Chief",
    status: "TBC",
    departmentId: "major-projects",
    projectId: "iba-amendment",
  },
  {
    id: "m3",
    dateLabel: "20 MAY",
    title: "Pathways dispute resolution",
    detail: "Legal & department sync",
    leads: "Leads: Terry · Lands",
    status: "TBC",
    departmentId: "lands",
    projectId: "referral-response",
  },
  {
    id: "m3b",
    dateLabel: "26 MAY",
    title: "Traditional use study check-in",
    detail: "Mapping progress review",
    leads: "Leads: Scott",
    status: "TBC",
    departmentId: "lands",
    projectId: "traditional-use",
  },
  {
    id: "m4",
    dateLabel: "22 MAY",
    title: "Housing allocation review",
    detail: "Waitlist & unit assignments",
    leads: "Leads: Maria · Chief",
    status: "TBC",
    departmentId: "housing",
    projectId: "allocation-2026",
  },
  {
    id: "m5",
    dateLabel: "27 MAY",
    title: "Capital projects status",
    detail: "Q2 budget checkpoint",
    leads: "Leads: Finance · Capital",
    status: "TBC",
    departmentId: "capital-projects",
    projectId: "community-hall",
  },
  {
    id: "m5b",
    dateLabel: "29 MAY",
    title: "Water infrastructure risk review",
    detail: "Contractor delay mitigation",
    leads: "Leads: Terry · Finance",
    status: "TBC",
    departmentId: "capital-projects",
    projectId: "water-infrastructure",
  },
  {
    id: "m6",
    dateLabel: "03 JUN",
    title: "Forestry permit briefing",
    detail: "Cutting permit package",
    leads: "Leads: Daniel · Chief",
    status: "TBC",
    departmentId: "forestry",
    projectId: "cutting-permit",
  },
  {
    id: "m7",
    dateLabel: "08 MAY",
    title: "Executive directives standup",
    detail: "Chief's Office weekly",
    leads: "Leads: Chief · Terry",
    status: "TBC",
    departmentId: "chiefs-office",
    projectId: "exec-directives",
  },
  {
    id: "m8",
    dateLabel: "21 MAY",
    title: "Q2 finance variance",
    detail: "Department budget review",
    leads: "Leads: Priya · Chief",
    status: "TBC",
    departmentId: "finance",
    projectId: "q2-budget",
  },
];

export const files: FileItem[] = [
  {
    id: "f1",
    name: "TKN Letter — Kemess North.pdf",
    department: "Major Projects",
    departmentId: "major-projects",
    status: "Awaiting signature",
    updated: "May 7, 2026",
    owner: "Terry",
    version: "v3.2",
    projectId: "kemess-north",
  },
  {
    id: "f2",
    name: "FPX Share-holding Brief.docx",
    department: "Major Projects",
    departmentId: "major-projects",
    status: "In review",
    updated: "May 6, 2026",
    owner: "Evan",
    version: "v1.4",
    projectId: "fpx",
  },
  {
    id: "f3",
    name: "Pathways Dispute Resolution.pdf",
    department: "Major Projects",
    departmentId: "major-projects",
    status: "Needs approval",
    updated: "May 5, 2026",
    owner: "Evan",
    version: "v2.0",
    projectId: "pathways",
  },
  {
    id: "f8",
    name: "IBA Amendment — Major Projects.pdf",
    department: "Major Projects",
    departmentId: "major-projects",
    status: "Awaiting signature",
    updated: "Apr 25, 2026",
    owner: "Terry",
    version: "v2.1",
    projectId: "iba-amendment",
  },
  {
    id: "f9",
    name: "Kemess Supporting Annex.pdf",
    department: "Major Projects",
    departmentId: "major-projects",
    status: "In review",
    updated: "May 7, 2026",
    owner: "Evan",
    version: "v1.0",
    projectId: "kemess-north",
  },
  {
    id: "f4",
    name: "Band Council Resolution — May.pdf",
    department: "Chief's Office",
    departmentId: "chiefs-office",
    status: "Signed",
    updated: "May 5, 2026",
    owner: "Chief French",
    version: "v1.0",
    projectId: "bcr-may",
  },
  {
    id: "f10",
    name: "Executive Directives Log.xlsx",
    department: "Chief's Office",
    departmentId: "chiefs-office",
    status: "Active",
    updated: "May 7, 2026",
    owner: "Chief French",
    version: "v2.3",
    projectId: "exec-directives",
  },
  {
    id: "f11",
    name: "Lands Referral Package.pdf",
    department: "Lands",
    departmentId: "lands",
    status: "Needs approval",
    updated: "May 6, 2026",
    owner: "Scott",
    version: "v1.2",
    projectId: "referral-response",
  },
  {
    id: "f12",
    name: "Traditional Use Map Draft.pdf",
    department: "Lands",
    departmentId: "lands",
    status: "Draft",
    updated: "May 4, 2026",
    owner: "Scott",
    version: "v0.6",
    projectId: "traditional-use",
  },
  {
    id: "f5",
    name: "Housing Allocation Letter.pdf",
    department: "Housing",
    departmentId: "housing",
    status: "Signed",
    updated: "May 2, 2026",
    owner: "Maria",
    version: "v1.1",
    projectId: "allocation-2026",
  },
  {
    id: "f13",
    name: "Housing Waitlist 2026.xlsx",
    department: "Housing",
    departmentId: "housing",
    status: "Active",
    updated: "May 6, 2026",
    owner: "Maria",
    version: "v3.0",
    projectId: "allocation-2026",
  },
  {
    id: "f6",
    name: "Q2 Capital Budget.xlsx",
    department: "Finance",
    departmentId: "finance",
    status: "Active",
    updated: "May 1, 2026",
    owner: "Priya",
    version: "v4.0",
    projectId: "q2-budget",
  },
  {
    id: "f7",
    name: "Forestry Cutting Permit Package.pdf",
    department: "Forestry",
    departmentId: "forestry",
    status: "Draft",
    updated: "Apr 28, 2026",
    owner: "Daniel",
    version: "v0.9",
    projectId: "cutting-permit",
  },
  {
    id: "f14",
    name: "Silviculture Plan Outline.docx",
    department: "Forestry",
    departmentId: "forestry",
    status: "Draft",
    updated: "May 3, 2026",
    owner: "Daniel",
    version: "v0.4",
    projectId: "silviculture",
  },
  {
    id: "f15",
    name: "Community Hall Specs.pdf",
    department: "Capital Projects",
    departmentId: "capital-projects",
    status: "Active",
    updated: "May 5, 2026",
    owner: "Terry",
    version: "v2.0",
    projectId: "community-hall",
  },
  {
    id: "f16",
    name: "Water Phase 2 Change Order.pdf",
    department: "Capital Projects",
    departmentId: "capital-projects",
    status: "Needs approval",
    updated: "May 7, 2026",
    owner: "Priya",
    version: "v1.1",
    projectId: "water-infrastructure",
  },
];

export const tasks: TaskItem[] = [
  {
    id: "tk1",
    title: "Kemess North — Final TKN letter",
    assignee: "Chief French",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "urgent",
    due: "May 13, 2026",
    status: "In progress",
    projectId: "kemess-north",
  },
  {
    id: "tk2",
    title: "FPX — Share-holding decision",
    assignee: "Chief French",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "high",
    due: "May 15, 2026",
    status: "Pending",
    projectId: "fpx",
  },
  {
    id: "tk3",
    title: "Aggregate bi-weekly progress updates",
    assignee: "Terry",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "urgent",
    due: "May 10, 2026",
    status: "In progress",
    projectId: "kemess-north",
  },
  {
    id: "tk4",
    title: "Upload Kemess supporting docs",
    assignee: "Evan",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "urgent",
    due: "May 9, 2026",
    status: "In progress",
    projectId: "kemess-north",
  },
  {
    id: "tk4b",
    title: "Pathways chronology for legal",
    assignee: "Evan",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "high",
    due: "May 14, 2026",
    status: "In progress",
    projectId: "pathways",
  },
  {
    id: "tk4c",
    title: "IBA amendment redlines",
    assignee: "Terry",
    department: "Major Projects",
    departmentId: "major-projects",
    priority: "high",
    due: "May 18, 2026",
    status: "Pending",
    projectId: "iba-amendment",
  },
  {
    id: "tk5",
    title: "Flag referral for Chief attention",
    assignee: "Scott",
    department: "Lands",
    departmentId: "lands",
    priority: "urgent",
    due: "May 12, 2026",
    status: "Pending",
    projectId: "referral-response",
  },
  {
    id: "tk5b",
    title: "Traditional use map draft",
    assignee: "Scott",
    department: "Lands",
    departmentId: "lands",
    priority: "high",
    due: "May 25, 2026",
    status: "In progress",
    projectId: "traditional-use",
  },
  {
    id: "tk6",
    title: "Allocation waitlist update",
    assignee: "Maria",
    department: "Housing",
    departmentId: "housing",
    priority: "high",
    due: "May 18, 2026",
    status: "In progress",
    projectId: "allocation-2026",
  },
  {
    id: "tk7",
    title: "Cutting permit package",
    assignee: "Daniel",
    department: "Forestry",
    departmentId: "forestry",
    priority: "urgent",
    due: "May 20, 2026",
    status: "Draft",
    projectId: "cutting-permit",
  },
  {
    id: "tk8",
    title: "Q2 budget variance report",
    assignee: "Priya",
    department: "Finance",
    departmentId: "finance",
    priority: "high",
    due: "May 22, 2026",
    status: "Pending",
    projectId: "q2-budget",
  },
  {
    id: "tk9",
    title: "Community hall contractor check-in",
    assignee: "Terry",
    department: "Capital Projects",
    departmentId: "capital-projects",
    priority: "high",
    due: "May 16, 2026",
    status: "Pending",
    projectId: "community-hall",
  },
  {
    id: "tk10",
    title: "Water phase 2 change order",
    assignee: "Priya",
    department: "Capital Projects",
    departmentId: "capital-projects",
    priority: "urgent",
    due: "May 14, 2026",
    status: "In progress",
    projectId: "water-infrastructure",
  },
  {
    id: "tk11",
    title: "Review open executive directives",
    assignee: "Chief French",
    department: "Chief's Office",
    departmentId: "chiefs-office",
    priority: "high",
    due: "May 10, 2026",
    status: "In progress",
    projectId: "exec-directives",
  },
];

export const currentUser = {
  name: "Chief French",
  role: "Chief's Office",
  initials: "JF",
  email: "chief.french@takla.ca",
};

export function getProjectsByDepartment(departmentId: string) {
  return projects.filter((p) => p.departmentId === departmentId);
}

export function getProjectById(projectId: string) {
  return projects.find((p) => p.id === projectId);
}

export function getFilesByProject(projectId: string) {
  return files.filter((f) => f.projectId === projectId);
}

export function getTasksByProject(projectId: string) {
  return tasks.filter((t) => t.projectId === projectId);
}

export function getApprovalsByProject(projectId: string) {
  return approvals.filter((a) => a.projectId === projectId);
}

export function getMeetingsByProject(projectId: string) {
  return meetings.filter((m) => m.projectId === projectId);
}

export function getApprovalsByDepartment(departmentId: string) {
  return approvals.filter((a) => a.departmentId === departmentId);
}

export function getMeetingsByDepartment(departmentId: string) {
  return meetings.filter((m) => m.departmentId === departmentId);
}

export function getFilesByDepartment(departmentId: string) {
  return files.filter((f) => f.departmentId === departmentId);
}

export function getTasksByDepartment(departmentId: string) {
  return tasks.filter((t) => t.departmentId === departmentId);
}

export function getTeamByDepartment(departmentId: string): TeamMember[] {
  return teamMembers
    .filter((m) => m.departmentIds.includes(departmentId))
    .map((m) => {
      const deptTasks = m.tasks.filter((t) => t.departmentId === departmentId);
      const urgentCount = deptTasks.filter((t) => t.priority === "urgent").length;
      const highCount = deptTasks.filter((t) => t.priority === "high").length;
      return {
        ...m,
        tasks: deptTasks.length ? deptTasks : m.tasks.filter((t) => !t.departmentId || t.departmentId === departmentId),
        urgentCount,
        highCount,
        taskCount: deptTasks.length || m.taskCount,
      };
    })
    .filter((m) => m.tasks.length > 0 || m.departmentIds[0] === departmentId);
}

export function getDepartmentOverview(departmentId: string) {
  const department = departments.find((d) => d.id === departmentId);
  const deptProjects = getProjectsByDepartment(departmentId);
  const deptTasks = getTasksByDepartment(departmentId);
  const deptFiles = getFilesByDepartment(departmentId);
  const deptApprovals = getApprovalsByDepartment(departmentId);
  const deptMeetings = getMeetingsByDepartment(departmentId);
  const deptTeam = getTeamByDepartment(departmentId);

  const urgent = deptTasks.filter((t) => t.priority === "urgent").length;
  const high = deptTasks.filter((t) => t.priority === "high").length;
  const completed = deptTasks.filter((t) => t.status === "Completed" || t.status === "Done").length
    + deptProjects.filter((p) => p.status === "completed").length;

  return {
    department,
    projects: deptProjects,
    tasks: deptTasks,
    files: deptFiles,
    approvals: deptApprovals,
    meetings: deptMeetings,
    team: deptTeam,
    stats: [
      {
        id: "active-files",
        label: "Active files",
        value: deptFiles.length,
        subtitle: department?.name ?? "Department",
        icon: "folder",
        color: "green",
      },
      {
        id: "total-tasks",
        label: "Total tasks",
        value: deptTasks.length || department?.taskCount || 0,
        subtitle: `${deptTeam.length} assignees`,
        icon: "list",
        color: "blue",
      },
      {
        id: "urgent",
        label: "Urgent",
        value: urgent || deptProjects.filter((p) => p.priority === "urgent").length,
        subtitle: "Action needed now",
        icon: "alert",
        color: "red",
      },
      {
        id: "high",
        label: "High priority",
        value: high || deptProjects.filter((p) => p.priority === "high").length,
        subtitle: "This month",
        icon: "star",
        color: "orange",
      },
      {
        id: "completed",
        label: "Completed",
        value: completed,
        subtitle: "This cycle",
        icon: "check",
        color: "green",
      },
    ] as Stat[],
  };
}
