import type { ProjectActivity, ProjectMessage, ProjectNote } from "./types";

/** Rich detail content keyed by project. Missing projects get generated fallbacks. */
export const projectMessages: ProjectMessage[] = [
  {
    id: "msg1",
    projectId: "kemess-north",
    author: "Terry",
    initials: "TR",
    role: "Executive Lead",
    body: "Chief — the final TKN letter package is assembled. Please review the annex before Thursday’s signature meeting.",
    timestamp: "May 7, 2026 · 9:12 AM",
  },
  {
    id: "msg2",
    projectId: "kemess-north",
    author: "Evan",
    initials: "EV",
    role: "Project Support",
    body: "Uploaded supporting annex v1.0 and linked it to the signature package. Waiting on legal confirmation of Schedule B.",
    timestamp: "May 7, 2026 · 8:45 AM",
  },
  {
    id: "msg3",
    projectId: "kemess-north",
    author: "Chief French",
    initials: "JF",
    role: "Chief's Office",
    body: "Hold the signature until Terry confirms Centerra’s redlines are closed. Flag me if anything slips past May 13.",
    timestamp: "May 6, 2026 · 4:20 PM",
  },
  {
    id: "msg4",
    projectId: "fpx",
    author: "Terry",
    initials: "TR",
    role: "Executive Lead",
    body: "Board memo is ready for Chief decision. Finance wants a 15-minute brief before we lock the share-holding position.",
    timestamp: "May 6, 2026 · 2:10 PM",
  },
  {
    id: "msg5",
    projectId: "fpx",
    author: "Priya",
    initials: "PR",
    role: "Finance",
    body: "I’ve attached the valuation summary. Recommend we discuss downside exposure before the NEXT WK meeting.",
    timestamp: "May 6, 2026 · 11:30 AM",
  },
  {
    id: "msg6",
    projectId: "pathways",
    author: "Evan",
    initials: "EV",
    role: "Project Support",
    body: "Dispute chronology draft is with legal. Scott — can Lands confirm the referral timeline by Friday?",
    timestamp: "May 5, 2026 · 3:40 PM",
  },
  {
    id: "msg7",
    projectId: "pathways",
    author: "Scott",
    initials: "SC",
    role: "Lands",
    body: "Confirmed. I’ll send the referral crosswalk tomorrow morning.",
    timestamp: "May 5, 2026 · 4:05 PM",
  },
  {
    id: "msg8",
    projectId: "iba-amendment",
    author: "Terry",
    initials: "TR",
    role: "Executive Lead",
    body: "IBA amendment redlines are open. Please review clauses 4.2 and 7.1 before the walkthrough on May 19.",
    timestamp: "May 4, 2026 · 10:15 AM",
  },
  {
    id: "msg9",
    projectId: "referral-response",
    author: "Scott",
    initials: "SC",
    role: "Lands",
    body: "Three referrals need Chief attention this week. Flagged the highest-risk package in Approvals.",
    timestamp: "May 6, 2026 · 1:00 PM",
  },
  {
    id: "msg10",
    projectId: "cutting-permit",
    author: "Daniel",
    initials: "DL",
    role: "Forestry",
    body: "Cutting permit package is at v0.9. Need silviculture map insert before Chief briefing on Jun 3.",
    timestamp: "May 3, 2026 · 9:50 AM",
  },
  {
    id: "msg11",
    projectId: "allocation-2026",
    author: "Maria",
    initials: "MK",
    role: "Housing",
    body: "Waitlist updated. Allocation letters ready for the May 22 review with Chief.",
    timestamp: "May 6, 2026 · 10:05 AM",
  },
  {
    id: "msg12",
    projectId: "water-infrastructure",
    author: "Priya",
    initials: "PR",
    role: "Finance",
    body: "Change order cost impact attached. At-risk until contractor confirms new timeline.",
    timestamp: "May 7, 2026 · 8:20 AM",
  },
];

export const projectNotes: ProjectNote[] = [
  {
    id: "n1",
    projectId: "kemess-north",
    author: "Terry",
    title: "Signature package checklist",
    body: "• TKN letter v3.2\n• Supporting annex\n• Centerra acknowledgment\n• Legal Schedule B confirmation\n• Chief signature slot May 13",
    updated: "May 7, 2026",
    pinned: true,
  },
  {
    id: "n2",
    projectId: "kemess-north",
    author: "Evan",
    title: "Open questions for Centerra",
    body: "Confirm whether Schedule B language from Apr 22 still stands. If not, escalate to Terry before packing the signature binder.",
    updated: "May 6, 2026",
  },
  {
    id: "n3",
    projectId: "fpx",
    author: "Priya",
    title: "Share-holding decision criteria",
    body: "Decision should weigh: dilution risk, governance rights, cash reserve impact, and political optics with membership.",
    updated: "May 6, 2026",
    pinned: true,
  },
  {
    id: "n4",
    projectId: "pathways",
    author: "Evan",
    title: "Dispute timeline notes",
    body: "Initial complaint Mar 12. Response draft Apr 2. Current brief incorporates Lands referral history and legal posture.",
    updated: "May 5, 2026",
  },
  {
    id: "n5",
    projectId: "iba-amendment",
    author: "Terry",
    title: "Clauses needing Chief attention",
    body: "4.2 employment targets · 7.1 revenue sharing formula · 9.0 dispute escalation path.",
    updated: "May 4, 2026",
    pinned: true,
  },
  {
    id: "n6",
    projectId: "referral-response",
    author: "Scott",
    title: "Priority referrals",
    body: "North parcel boundary · Mining access corridor · Seasonal road use request.",
    updated: "May 6, 2026",
  },
  {
    id: "n7",
    projectId: "housing",
    author: "Maria",
    title: "Allocation principles",
    body: "Seniority on waitlist, household size fit, medical priority, and maintenance readiness of unit.",
    updated: "May 2, 2026",
  },
  {
    id: "n8",
    projectId: "allocation-2026",
    author: "Maria",
    title: "Allocation principles",
    body: "Seniority on waitlist, household size fit, medical priority, and maintenance readiness of unit.",
    updated: "May 2, 2026",
    pinned: true,
  },
  {
    id: "n9",
    projectId: "cutting-permit",
    author: "Daniel",
    title: "Permit package contents",
    body: "Harvest block map, silviculture prescription, wildlife buffer notes, contractor insurance certificates.",
    updated: "Apr 28, 2026",
  },
  {
    id: "n10",
    projectId: "water-infrastructure",
    author: "Terry",
    title: "Risk register",
    body: "Contractor delay · Seasonal freeze window · Change order approval path through Finance and Chief.",
    updated: "May 7, 2026",
    pinned: true,
  },
  {
    id: "n11",
    projectId: "community-hall",
    author: "Terry",
    title: "Scope notes",
    body: "Accessibility ramp, kitchen upgrade, roof membrane, AV booth — keep gym floor out of Phase 1.",
    updated: "May 5, 2026",
  },
  {
    id: "n12",
    projectId: "q2-budget",
    author: "Priya",
    title: "Variance watchlist",
    body: "Major Projects over by 1.8% · Capital under on labour · Forestry overtime spike in April.",
    updated: "May 1, 2026",
    pinned: true,
  },
  {
    id: "n13",
    projectId: "exec-directives",
    author: "Chief French",
    title: "Open directives",
    body: "1) Close Kemess signature 2) FPX decision this month 3) Housing allocation letters out by May 22.",
    updated: "May 7, 2026",
    pinned: true,
  },
];

export const projectActivities: ProjectActivity[] = [
  {
    id: "act1",
    projectId: "kemess-north",
    type: "file",
    actor: "Evan",
    summary: "Uploaded Kemess Supporting Annex.pdf (v1.0)",
    timestamp: "May 7, 2026 · 8:40 AM",
  },
  {
    id: "act2",
    projectId: "kemess-north",
    type: "message",
    actor: "Terry",
    summary: "Messaged Chief about signature package readiness",
    timestamp: "May 7, 2026 · 9:12 AM",
  },
  {
    id: "act3",
    projectId: "kemess-north",
    type: "approval",
    actor: "System",
    summary: "TKN letter moved to Ready for Chief signature",
    timestamp: "May 7, 2026 · 7:55 AM",
  },
  {
    id: "act4",
    projectId: "kemess-north",
    type: "task",
    actor: "Evan",
    summary: "Updated task: Upload Kemess supporting docs → In progress",
    timestamp: "May 6, 2026 · 5:10 PM",
  },
  {
    id: "act5",
    projectId: "kemess-north",
    type: "meeting",
    actor: "Terry",
    summary: "Scheduled Kemess North — Final TKN letter for 13 MAY",
    timestamp: "May 5, 2026 · 2:00 PM",
  },
  {
    id: "act6",
    projectId: "kemess-north",
    type: "note",
    actor: "Terry",
    summary: "Pinned note: Signature package checklist",
    timestamp: "May 5, 2026 · 11:20 AM",
  },
  {
    id: "act7",
    projectId: "fpx",
    type: "file",
    actor: "Evan",
    summary: "Updated FPX Share-holding Brief.docx to v1.4",
    timestamp: "May 6, 2026 · 1:45 PM",
  },
  {
    id: "act8",
    projectId: "fpx",
    type: "approval",
    actor: "System",
    summary: "FPX board memo queued for Decide",
    timestamp: "May 6, 2026 · 12:00 PM",
  },
  {
    id: "act9",
    projectId: "pathways",
    type: "message",
    actor: "Evan",
    summary: "Asked Lands to confirm referral timeline",
    timestamp: "May 5, 2026 · 3:40 PM",
  },
  {
    id: "act10",
    projectId: "iba-amendment",
    type: "status",
    actor: "Terry",
    summary: "Progress updated to 55%",
    timestamp: "May 4, 2026 · 4:30 PM",
  },
  {
    id: "act11",
    projectId: "water-infrastructure",
    type: "approval",
    actor: "Priya",
    summary: "Submitted change order for Capital spend approval",
    timestamp: "May 7, 2026 · 8:15 AM",
  },
  {
    id: "act12",
    projectId: "allocation-2026",
    type: "file",
    actor: "Maria",
    summary: "Updated Housing Waitlist 2026.xlsx to v3.0",
    timestamp: "May 6, 2026 · 9:50 AM",
  },
];

export function getMessagesForProject(projectId: string): ProjectMessage[] {
  const found = projectMessages.filter((m) => m.projectId === projectId);
  if (found.length) return found;
  return [
    {
      id: `msg-fallback-${projectId}`,
      projectId,
      author: "Terry",
      initials: "TR",
      role: "Executive Lead",
      body: "Kickoff notes captured. Use this thread for blockers and Chief-facing updates.",
      timestamp: "May 1, 2026 · 10:00 AM",
    },
  ];
}

export function getNotesForProject(projectId: string): ProjectNote[] {
  const found = projectNotes.filter((n) => n.projectId === projectId);
  if (found.length) return found;
  return [
    {
      id: `note-fallback-${projectId}`,
      projectId,
      author: "System",
      title: "Project notebook",
      body: "Add working notes, decisions, and follow-ups for this file here.",
      updated: "May 1, 2026",
    },
  ];
}

export function getActivitiesForProject(projectId: string): ProjectActivity[] {
  const found = projectActivities.filter((a) => a.projectId === projectId);
  if (found.length) return found;
  return [
    {
      id: `act-fallback-${projectId}`,
      projectId,
      type: "status",
      actor: "System",
      summary: "Project created in the portal",
      timestamp: "May 1, 2026 · 9:00 AM",
    },
  ];
}
